config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:show, :edit, :update, :destroy]
end

# GET "cocktails/42/doses/new"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :image, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :ingredient, uniqueness: {scope: :cocktail}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # belongs_to :cocktail
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to @coctail
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end


  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :image)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
      raise
    end
  end


  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="main-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 offset-sm-2 col-sm-8">
        <%=simple_form_for [@cocktail] do |f| %>
          <%= f.input :name, label: "Cocktail Name" %>
          <%= f.input :image %>
          <%= f.input :image_cache, as: :hidden %>
          <%= f.submit "add cocktail", class: "btn btn-ghost border-dark rounded-lg"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<div class="heading">
  <h1>Cocktails#edit</h1>
</div>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner">
  <h1>Cocktails</h1>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
    </div>
  </div>
</div>
<div class="main-container">
  <!-- <div class="cards"> -->
  <div class="cards" >
    <% @cocktails.each do |cocktail| %>
      <div class="card" style="background-image: url('<%=cl_image_path cocktail.image %>')">
        <%#= image_tag "#{cocktail.image}"%>
        <%= link_to cocktail.name, cocktail_path(cocktail.id) %>
      </div>
    <% end %>
  </div>
  <!-- </div> -->
</div>
<%#=link_to "Add cocktail", new_cocktail_path%>
<!--
  <div class="d-inline-flex p-1">
    <li>
      <%#= link_to cocktail.name, cocktail_path(cocktail.id) %>
       <p><%#= link_to "Delete", cocktail_path(cocktail.id), method: :delete, data: {confirm: 'Are you sure?'} %></p>
    </li> -->

app/views/cocktails/new.html.erb
<div class="heading">
  <h1>Cocktails</h1>
</div>
<%= render 'form', cocktail: @cocktail%>

app/views/cocktails/show.html.erb
<div class="show-container">
  <div class="show-image" style="background-image: url('<%=cl_image_path @cocktail.image %>')";>
  </div>
  <%#= image_tag ""%>
  <div class="card-description">
    <h4>
      <%= "Cocktail : #{@cocktail.name}" %>
    </h4>
    <h5>
      Ingredients :
    </h5>
    <p>
      <% @doses.each do |dose| %>
        <p>
          <%= "description: #{dose.description}" %>
        </p>
      <% end %>
    </p>
  </div>
  <div class="opt-container">
    <p>
      <%= link_to cocktail_path(@cocktail.id), method: :delete, data: {confirm: 'Are you sure?'} do %>
        <i class="far fa-trash-alt"></i> <% end %> | <%=link_to new_cocktail_dose_path(@cocktail.id) do %>
        <i class="far fa-edit"></i>
      <% end %>
    </p>
  </div>
</div>
<!-- <p>
    <%=link_to "Homepage", cocktails_path%>
  </p> -->
<%# @doses.each do |dose| %>
  <%#= "name: #{@cocktail.name}" %>
  <%#= "description: #{dose.description}" %>
  <%# end %>

app/views/doses/_form.html.erb
<%=simple_form_for [@cocktail, @dose] do |f| %>
<% end %>

app/views/doses/new.html.erb
<div class="heading">
  <h1>Ingredients</h1>
</div>
<div class="main-container">
  <div class="container">
    <div class="bckgrnd">
      <div class=" ">
        <div class="col-xs-12 offset-sm-2 col-sm-8 ">
          <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.association :ingredient%>
            <%= f.input :description %>
            <%= f.submit "add ingredient", class: "btn btn-ghost border-dark rounded-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-custom fixed-top">
  <%#= link_to "#", class: "navbar-brand" do %>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <%# end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", cocktails_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Add Cocktail",new_cocktail_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0 ">
        <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-ghost border-dark rounded-lg m-2 my-sm-0 pull-right" type="submit">Search</button>
      </form>
    </div>
  </div>